version: '3.3'
services:
  web:
    image: vandrucha77/mytestapp:test
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 12M
    ports:
     - "8082:5000"