version: '3.3'
services:
    my-funny-app:
        image: dtr01.andreas.dtcntr.net/docker-cemea/my-test-app:180109205219
        deploy:
            mode: replicated
            replicas: 3
            update_config:
              parallelism: 1
              delay: 2s
              max_failure_ratio: 0.2
              failure_action: pause
              #  order: stop-first
            restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 1
              window: 0s
            labels:
                com.docker.ucp.mesh.http.5000: "external_route=http://my-test-app.andreas.dtcntr.net,internal_port=5000"
                com.docker.ucp.access.label: /Development
        healthcheck:
          interval: 5s
          timeout: 1s
          retries: 3
        ports:
            - 8087:5000
        networks:
            - my-test-app
            - ucp-hrm

networks:
    my-test-app:
    ucp-hrm:
        external: true